version: '3'
services:
  minio-service:
    container_name: minio-service
    build:
      context: ./minio
      dockerfile: dockerfile
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=jganggang@!123
    volumes:
    - /root/app/minio/data:/data
    - /root/app/minio/config:/root/.minio
    restart: always
    ports:
    - 9000:9000
    - 9090:9090
    command: server --console-address ":9090" -address ":9000" /data

