# Minio配置
minio:
  endpoint: http://www.xiaowenhao.ren:9000
  accesskey: minioadmin
  secretkey: jganggang@!123
  bucketName: public

# 数据库配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://aliyun.xiaowenhao.ren:3306/sys_minio?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 4234
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
  servlet:
    context-path: /mi

#mpmbredis:
#  redis:
#    defaultdb:
#      host: aliyun.xiaowenhao.ren
#      port: 6379
#      password: 4234
#    mpmb:
#      host: aliyun.xiaowenhao.ren
#      port: 6379
#      password: 4234
