# Minio配置
minio:
  endpoint: http://url:host
  accesskey: account
  secretkey: password
  bucketName: bucketName

# 数据库配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://url:3306/sys_minio?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: username
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
  servlet:
    context-path: /
