# 开发环境配置
server:
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
# Spring配置
spring:
  servlet:
    multipart:
      # 上传文件大小限制
      max-file-size: 5120MB
      max-request-size: 5120MB
  profiles:
    active: druid, dev

# 日志配置
logging:
  level:
    com.minio: debug
    org.springframework: warn


# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.minio.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
