# 开发环境配置
server:
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
# Spring配置
spring:
  servlet:
    multipart:
      # 上传文件大小限制
      max-file-size: 5120MB
      max-request-size: 5120MB
  profiles:
    active: druid, dev

# 日志配置
logging:
  level:
    com.minio: debug
    org.springframework: warn

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapperLocations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.minio.**.domain
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
